Remove play button/Start timer only when a game is started/Refactor g…
binarytrails/kakuro pull request #48
Opened 2020-03-10 01:42 UTC by joshpham97

…ame difficulty selection

2020-03-11 02:04 UTC, joshpham97 commented
I will remove one of them later, since we do not need both.

2020-03-11 02:06 UTC, binarytrails commented
> I will remove one of them later, since we do not need both.

@joshpham97 got it! perhaps, a TODO  comment would be useful cause I couldn't understand

2020-03-11 03:03 UTC, joshpham97 commented
Oh my bad I forgot to put it

2020-03-12 18:14 UTC, binarytrails commented
@joshpham97 
to merge with ``` git rebase -i master```, I use http://meldmerge.org/ you can do ```git mergetool=meld``` and keep going with ```git merge --continue``` until it is all good and then ```git push -f```

2020-03-12 23:12 UTC, binarytrails requested changes

2020-03-12 23:12 UTC, binarytrails commented on diaries/diary_TiffanyAH KING.tex
> +\section{Iteration 2}
that is strange it is already on master see: https://github.com/binarytrails/kakuro/commit/a26843f41e33c9e99ada0b5c32e45b9dff65bbed

2020-03-12 23:12 UTC, binarytrails commented on tests/kakuro/TestPlayerDao.java
> +	public void testRegisterAlreadyRegistered(){
same for tests already on master, there is something odd here

2020-03-12 23:12 UTC, binarytrails commented
in any cases the tests gotta pass ! aim for that

2020-03-13 00:36 UTC, closed without merging